name: Build Executables

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            executable_name: GoogleFitSync.exe
            build_command: pyinstaller --onefile --windowed --add-data "oauth_config.json;." --name GoogleFitSync main.py
          - os: macos-latest
            executable_name: GoogleFitSync
            build_command: pyinstaller --onefile --windowed --add-data "oauth_config.json:." --name GoogleFitSync main.py
          - os: ubuntu-latest
            executable_name: GoogleFitSync
            build_command: pyinstaller --onefile --windowed --add-data "oauth_config.json:." --name GoogleFitSync main.py

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Create OAuth config file
      run: |
        echo '{"client_id": "${{ secrets.GOOGLE_CLIENT_ID || '340362959053-mpj1ck0j6oj568reff7rdo7fd8in46d4.apps.googleusercontent.com' }}", "client_secret": "${{ secrets.GOOGLE_CLIENT_SECRET || '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' }}"}' > oauth_config.json
    
    - name: Build executable
      env:
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      run: ${{ matrix.build_command }}
    
    - name: Fix macOS permissions and signing
      if: matrix.os == 'macos-latest'
      run: |
        chmod +x dist/GoogleFitSync
        # Remove quarantine attribute to prevent Gatekeeper issues
        xattr -d com.apple.quarantine dist/GoogleFitSync || true
    
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: GoogleFitSync-${{ matrix.os }}
        path: dist/${{ matrix.executable_name }}
        retention-days: 90

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
    - name: Download Windows executable
      uses: actions/download-artifact@v4
      with:
        name: GoogleFitSync-windows-latest
        path: ./windows/
    
    - name: Download macOS executable
      uses: actions/download-artifact@v4
      with:
        name: GoogleFitSync-macos-latest
        path: ./macos/
    
    - name: Download Linux executable
      uses: actions/download-artifact@v4
      with:
        name: GoogleFitSync-ubuntu-latest
        path: ./linux/
    
    - name: Create release archives
      run: |
        cd windows && zip -r ../GoogleFitSync-Windows.zip GoogleFitSync.exe
        cd ../macos && zip -r ../GoogleFitSync-macOS.zip GoogleFitSync
        cd ../linux && zip -r ../GoogleFitSync-Linux.zip GoogleFitSync
    
    - name: Upload release assets
      uses: softprops/action-gh-release@v1
      with:
        files: |
          GoogleFitSync-Windows.zip
          GoogleFitSync-macOS.zip
          GoogleFitSync-Linux.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

